openapi: 3.0.0
info:
  title: Ticket Service API
  version: 1.0.0
  description: API for creating, managing, and resolving support tickets.

servers:
  - url: http://localhost:5001/api

paths:
  /tickets:
    get:
      summary: Retrieve all tickets
      tags: [Tickets]
      responses:
        '200':
          description: A list of support tickets
    post:
      summary: Create a new support ticket
      tags: [Tickets]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                message:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Ticket created successfully

  /tickets/{id}:
    put:
      summary: Update ticket status
      tags: [Tickets]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [open, in progress, resolved]
      responses:
        '200':
          description: Ticket status updated

    delete:
      summary: Delete a ticket
      tags: [Tickets]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ticket deleted successfully

  /tickets/ai-response:
    post:
      summary: Generate AI-powered response (future extension)
      tags: [AI]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: AI-generated response returned
